linters-settings:
  goimports:
    local-prefixes: github.com/synthesio/zconfig
  govet:
    check-shadowing: true
  misspell:
    locale: US
  unused:
    check-exported: false

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gosec
  disable:
    - structcheck # deprecated
    - varcheck   # deprecated
    - deadcode   # deprecated

issues:
  exclude-rules:
    # Allow unused parameters in interface implementations
    - path: _test\.go
      linters:
        - unparam
        - gosec
    # Exclude some golangci-lint rules for test files
    - path: testdata/
      linters:
        - unused
        - deadcode

run:
  timeout: 5m
  tests: true